# Generated by Django 3.0.3 on 2021-12-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_id', models.CharField(max_length=256)),
                ('clade', models.CharField(max_length=256)),
                ('genus', models.CharField(max_length=256)),
                ('species', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=256)),
                ('sequence', models.CharField(blank=True, max_length=40000)),
            ],
        ),
        migrations.CreateModel(
            name='ProteinDomainAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='midterm_api.Domain')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='midterm_api.Organism')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='midterm_api.Protein')),
            ],
        ),
    ]
