# Generated by Django 3.0.3 on 2021-12-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midterm_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proteindomainassignment',
            name='length',
        ),
        migrations.RemoveField(
            model_name='proteindomainassignment',
            name='start',
        ),
        migrations.RemoveField(
            model_name='proteindomainassignment',
            name='stop',
        ),
        migrations.AddField(
            model_name='domain',
            name='start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='stop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protein',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='sequence',
            field=models.CharField(blank=True, max_length=40000, null=True),
        ),
    ]
