# Generated by Django 3.0.3 on 2021-12-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midterm_api', '0004_auto_20211230_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
