# Generated by Django 3.0.3 on 2021-12-30 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midterm_api', '0005_auto_20211230_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='organism',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='midterm_api.Organism'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protein',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
