# Generated by Django 3.0.3 on 2021-12-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midterm_api', '0008_auto_20211230_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='id',
        ),
        migrations.AlterField(
            model_name='protein',
            name='protein_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
