# Generated by Django 3.0.3 on 2021-12-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midterm_api', '0009_auto_20211230_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='organism',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='protein',
        ),
    ]
