# Generated by Django 3.0.3 on 2021-12-30 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midterm_api', '0010_auto_20211230_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='organism',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='midterm_api.Organism'),
        ),
        migrations.AddField(
            model_name='domain',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='domains', to='midterm_api.Protein'),
        ),
    ]
