# Generated by Django 3.0.3 on 2021-12-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midterm_api', '0011_auto_20211230_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='protein',
            new_name='protein_id',
        ),
    ]
